version: '3'
services:
  web:
    container_name: '${APP_NAME}_web'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './Backend/:/var/www/app'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    links:
      - php
    ports:
      - '80:80'
      - '443:443'
    networks:
      - proxy
  front:
    container_name: '${APP_NAME}_front'
    build:
      context: ./Frontend
    hostname: client
    volumes:
      - './Frontend:/var/www/app'
    networks:
      - proxy
    ports:
      - '3000:3000'
    tty: true
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; npm install ; npm run build ; npm run start; done & npm install ; npm run build ;npm run start'''
  panel:
    container_name: '${APP_NAME}_panel'
    build:
      context: ./Panel
    hostname: client
    volumes:
      - './Panel:/var/www/app'
    networks:
      - proxy
    ports:
      - '3001:3000'
    tty: true
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; npm install http-server -g && npm install --no-optional && npm run build &&  http-server ./dist;  done & npm install ; npm run build ;npm run preview'''
  php:
    container_name: '${APP_NAME}_php'
    image: mndco/sample-php:1
#    build:
#      context: ./Backend
#      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
    volumes:
      - './Backend/:/var/www/app'
    networks:
      - proxy
  db:
    container_name: '${APP_NAME}_db'
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - '/var/lib/mysql_volume:/var/lib/mysql'
    networks:
      - proxy
    cap_add:
      - SYS_NICE
  myadmin:
    container_name: '${APP_NAME}_myadmin'
    image: phpmyadmin
    ports:
      - '81:80'
    environment:
      UPLOAD_LIMIT: 300M
    depends_on:
      - db
    networks:
      - proxy
networks:
  proxy:
    driver: bridge

