<?php

namespace App\Models\Blog;

use App\Models\BaseModel;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Support\Str;

class Category extends BaseModel
{
    use HasFactory;

    protected $fillable = ['title'];

    protected static function boot()
    {
        static::creating(function (self $category){
            $category->slug = Str::slug($category->title);
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function scopeSearch($query, $word)
    {
        return $query->where('title', 'like', "%{$word}%");
    }
}
